### ISSUE TITLE
Problem to publish the award notice

### ISSUE THREAD

**Issue by philipmora** [innovasion-dk/ETHICS-Support#1]
There is a problem to publish the award notice in the tender "09.01 Združená dodávka zemného plynu od VO" for organisation ID=1321. The menu/button for publishing the notice is missing. The notice is already published in the local journal. Please could you fix it? Link to the award notice: https://evo.gov.sk/evo/ethics.nsf/tenderingcolor/838262654154E6E5C1257F2A002844ED Link to the tender: https://evo.gov.sk/evo/ethics.nsf/tenderingcolor/5E1B83733C1624DAC1257EC2003B0DE6?OpenDocument

**Comment by test-innovasion-dk** [comment]
kommentar

**Comment by bckfnn** [comment]
modsvar

2016-01-08 13:43 GMT+01:00 test-innovasion-dk <notifications@github.com>:
